logging.level:
  org.zalando.logbook: INFO

spring:
  output:
    ansi.enabled: always
  sql:
    init.mode: always
  jpa:
    hibernate:
      ddl-auto: none
  profiles:
    active: ci
    
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:file:./db/shareit
    driverClassName: org.h2.Driver
    username: sa
    password: password

---
spring:
  config:
    activate:
      on-profile: ci
  datasource:
    url: jdbc:postgresql://localhost:5432/shareit
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres