logging.level:
  org.zalando.logbook: INFO

spring:
  output:
    ansi.enabled: always
  sql:
    init.mode: always
  datasource:
    url: jdbc:h2:file:./db/shareit
    driverClassName: org.h2.Driver
    username: sa
    password: password